name: Auto Assign

on:
  workflow_call:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: o-nnerb,rodrigohtc
          numOfAssignee: 2
          allowSelfAssign: false
